### ISSUE TITLE
Cannot set Visibility to Visible or call Show, ShowDialog, Close, or WindowInteropHelper.EnsureHandle while a Window is closing

### ISSUE THREAD

**Issue by neominky** [Platonenkov/Notification.Wpf#66]
Four errors of three types occur together.
```
System.InvalidOperationException: Cannot set Visibility to Visible or call Show, ShowDialog, Close, or WindowInteropHelper.EnsureHandle while a Window is closing.
   at System.Windows.Window.VerifyNotClosing()
   at System.Windows.Window.Show()
   at Notification.Wpf.NotificationManager.ShowContent(Object content, Nullable`1 expirationTime, String areaName, Action onClick, Action onClose, Boolean CloseOnClick, Boolean ShowXbtn)
   at Notification.Wpf.NotificationManager.Show(Object content, String areaName, Nullable`1 expirationTime, Action onClick, Action onClose, Boolean CloseOnClick, Boolean ShowXbtn)
```

```
System.Runtime.InteropServices.COMException (0x88980406): UCEERR_RENDERTHREADFAILURE (0x88980406)
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.Composition.DUCE.Channel.SyncFlush()
   at System.Windows.Interop.HwndTarget.UpdateWindowSettings(Boolean enableRenderTarget, Nullable`1 channelSet)
   at System.Windows.Interop.HwndTarget.UpdateWindowPos(IntPtr lParam)
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

```
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Running on 1000 clients. About 15% have problems.
Sometimes, an error like this occurs on some PCs.
Once an error occurs, it will continue to occur.
This only happens on the PC where the error occurred. Any PC with the same hardware will get the error.
It may also appear along with the problem below. An out of memory error also appears. However, the problem cannot be resolved using the guided method.

https://learn.microsoft.com/en-us/troubleshoot/developer/dotnet/framework/general/wpf-render-thread-failures
There are also reports that the second monitor stops working when an error occurs.
Other WPF windows work fine. It only appears when show the Notification window.
Is there a memory leak issue?
There is no problem in the development or test environment. I tried running it for more than a week.

**Comment by Platonenkov** [comment]
The `InvalidOperationException` ("Cannot set Visibility to Visible ... while a Window is closing") is fixed in the upcoming **v10** (branch `dev`).

`ShowContent` now drops the overlay-window reference on `Closing` — so a concurrent `Show()` recreates a fresh window instead of touching one that is mid-close — and guards `Window.Show()` against a closing window:

```csharp
_window.Closing += (_, _) => { _window = null; };
_window.Closed  += (_, _) => { _window = null; };
// ...
try { _window.Show(); }
catch (InvalidOperationException) { _window = null; return; }
```

> The accompanying `UCEERR_RENDERTHREADFAILURE` and `OutOfMemoryException` are WPF GPU render-thread failures ([MS troubleshooting article](https://learn.microsoft.com/troubleshoot/developer/dotnet/framework/general/wpf-render-thread-failures)) — environmental, not caused by the library. The library-side `InvalidOperationException` is the part addressed here.

Code: [`NotificationManager.cs`](https://github.com/Platonenkov/Notification.Wpf/blob/dev/src/Notification.Wpf/Base/NotificationManager.cs) — see `ShowContent`.

**Comment by Platonenkov** [comment]
Fixed in v10 — see PR #76 and the comment above for usage and code links.
